# Generated by Django 6.0.5 on 2026-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('flashcards_due', '🃏 Flashcards à revoir'), ('streak_danger', '🔥 Streak en danger'), ('streak_broken', '💔 Streak cassé'), ('level_up', '⭐ Niveau supérieur'), ('exam_unlocked', '🏆 Examen débloqué'), ('welcome', '👋 Bienvenue'), ('weak_points', '🎯 Points faibles détectés')], max_length=30),
        ),
    ]
