# Generated by Django 6.0.5 on 2026-05-30 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_flashcard_ease_factor_flashcard_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_review_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
