# Generated by Django 6.0.5 on 2026-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_mastery_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='key_concepts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
