# Generated by Django 6.0.5 on 2026-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_estimated_mastery_time_course_key_concepts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='concept_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_difficulty',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_study_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='mastery_score',
            field=models.FloatField(default=0.0),
        ),
    ]
