# Generated by Django 6.0.5 on 2026-06-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/')),
                ('summary', models.JSONField(blank=True, null=True)),
                ('key_concepts', models.JSONField(blank=True, null=True)),
                ('estimated_mastery_time', models.CharField(blank=True, max_length=50)),
                ('concept_count', models.IntegerField(default=0)),
                ('course_difficulty', models.CharField(blank=True, max_length=10)),
                ('estimated_study_time_minutes', models.IntegerField(default=0)),
                ('course_type', models.CharField(blank=True, max_length=50)),
                ('photos_count', models.IntegerField(default=0)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
