services:
  - type: web
    name: revio-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.14"
      - key: DEBUG
        value: "False"
    healthCheckPath: /api/auth/profile/
